### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by isaacmichaud** [jasonmhite/gefry3#1]
setup.py has two different license lines which throws an error when installing

`  File "setup.py", line 10
    license="2-clause BSD (FreeBSD)",
SyntaxError: keyword argument repeated`

**Comment by jasonmhite** [comment]
Ahh good catch, not sure how that slipped through. Will fix it tomorrow, though obviously it'll work if you just delete it. "2-clause BSD" is the intended license.

**Comment by jasonmhite** [comment]
@isaacmichaud OK so I had this fixed in the branch that implements detector orientation. I decided to just merge this branch into master, since it's what I've been using anyway. If you merge/rebase onto master it should be fixed.

The other changes should be backwards compatible, lemme know if you have trouble.

This also introduces an optional dependency on my code for calculating solid angles, which is [here](https://github.com/jasonmhite/pyst). I think I have it set up correctly so that you only need this if you want to use the `OrientedPrismDetector` class, but if you have issues again lemme know.

**Comment by isaacmichaud** [comment]
Awesome! Thanks Jason
