### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by isaacmichaud** [jasonmhite/gefry3#2]
I was reinstalling the new version of your package and kept getting import errors: 

![image](https://user-images.githubusercontent.com/19880770/38098965-5b02f700-3347-11e8-8fc1-deb343f03856.png)

The above was fixed by changing line 7 of `setup.py` to:

```packages=["gefry3","gefry3.classes"],```

Also, I got an error because `hardware.py` imports `pyst` even though it is not a required package. Should it be made a required package in `setup.py`?

**Comment by jasonmhite** [comment]
Should be fixed in 84784a9. That makes the loading of classes related to `pyst` conditional on it being installed. Which was the intent... I just forgot to actually make it conditional. 

Also adds `gefry3.classes` to the packages line as you suggest. Not sure why that wasn't an error for me. I develop for Python 3 and I know they tweaked relative imports somewhat, might be that they changed how subpackages are exported so that what I was doing isn't an error in Py3K. Either way I fixed it and it should be ok on Py2.7 from my tests.

Lastly, added `pyyaml` to the `install_requires`. I think this is included by default in Anaconda so I forgot about it, but it should be required.

Lemme know if this works for you.
